PY = python3
##To use variables use $(var_name)
q7: logic.py utils.py
	$(PY) logic.py
	echo "Successfully executed"
logic.py:
	echo "File doesnt exist"
utils.py:
	echo "Define the utility file please"

test:test.py
	$(PY) test.py

test.py:
	echo "Create test.py file first"